### ISSUE TITLE
can not read property 'after' of undefined

### ISSUE THREAD

**Issue by srikanthkonline** [clinical-meteor/hl7-resource-observation#2]
In the following code, the error in the subject occurs though Observations is imported from meteor/clinical:hl7-resource observation

"Observations.after.insert(function (userId, doc) {"

**Comment by srikanthkonline** [comment]
Following are the versions.

clinical:alert@2.1.3
clinical:base-model@1.3.5
clinical:extended-api@2.2.4
clinical:fonts@1.1.6
clinical:glass-ui@2.1.6
clinical:hl7-resource-bundle@1.3.14
clinical:hl7-resource-datatypes@3.0.1
clinical:hl7-resource-diagnostic-report@1.5.12

**clinical:hl7-resource-observation@1.3.20**

**Comment by srikanthkonline** [comment]
METEOR@1.7.0.3

**Comment by awatson1978** [comment]
Ah, that's the issue I think.  `METEOR@1.7.03` is considerably more strict around globals, and requires additional imports in our HL7-* packages.  

Try one of the following, and let me know if any of them work (they're all variations on the same theme).
```
meteor update --release METEOR@1.6.0.1  
meteor update --release METEOR@1.6.1_3
meteor --release clinical:METEOR@1.6.0.1-rc20
meteor update --release clinical:METEOR@1.6.0.1-rc20
```

**Comment by srikanthkonline** [comment]
It didn't solve the issue. It skips with 1.6.0.1 when I run the app. Facing package constraints. with 1.6.1.3.

** following is the error message.**

=> Meteor 1.7.0.3 is available. Update this project with 'meteor update'.
Errors prevented startup:

While selecting package versions:
error: Potentially incompatible change required to top-level dependency: mongo 1.4.7, was 1.5.0.
Constraints on package "mongo":
* mongo@1.4.2 <- top level
* mongo@~1.4.2 <- top level
* mongo@1.4.2 <- autoupdate 1.4.0 <- hot-code-push 1.0.4 <- meteor-base 1.3.0
* mongo@1.1.10 <- pcci:sepsis-risk-model 0.1.11
* mongo@1.1.7 <- meteor-platform 1.2.6 <- clinical:base-model 1.3.5 <- clinical:hl7-resource-bundle 1.3.14 <- clinical:hl7-resource-diagnostic-report 1.5.12
* mongo@1.1.7 <- meteor-platform 1.2.6 <- clinical:base-model 1.3.5 <- clinical:hl7-resource-diagnostic-report 1.5.12
* mongo@1.1.7 <- meteor-platform 1.2.6 <- clinical:hl7-resource-diagnostic-report 1.5.12
* mongo@1.3.0 <- reactive-dict 1.2.0 <- clinical:extended-api 2.2.4 <- clinical:hl7-resource-diagnostic-report 1.5.12
* mongo@1.1.0 <- clinical:glass-ui 2.1.6 <- clinical:hl7-resource-diagnostic-report 1.5.12
* mongo@1.1.0 <- clinical:base-model 1.3.5 <- clinical:hl7-resource-bundle 1.3.14 <- clinical:hl7-resource-diagnostic-report 1.5.12
* mongo@1.1.0 <- clinical:base-model 1.3.5 <- clinical:hl7-resource-diagnostic-report 1.5.12
* mongo@1.0.4 <- aldeed:collection2 2.5.0 <- clinical:base-model 1.3.5 <- clinical:hl7-resource-bundle 1.3.14 <- clinical:hl7-resource-diagnostic-report 1.5.12
* mongo@1.0.4 <- aldeed:collection2 2.5.0 <- clinical:base-model 1.3.5 <- clinical:hl7-resource-diagnostic-report 1.5.12
* mongo@1.0.4 <- aldeed:collection2 2.5.0 <- clinical:hl7-resource-diagnostic-report 1.5.12
* mongo@1.1.0 <- matb33:collection-hooks 0.7.15 <- clinical:base-model 1.3.5 <- clinical:hl7-resource-bundle 1.3.14 <- clinical:hl7-resource-diagnostic-report 1.5.12
* mongo@1.1.0 <- matb33:collection-hooks 0.7.15 <- clinical:base-model 1.3.5 <- clinical:hl7-resource-diagnostic-report 1.5.12
* mongo@1.1.0 <- matb33:collection-hooks 0.7.15 <- clinical:hl7-resource-diagnostic-report 1.5.12
* mongo@1.1.5 <- percolate:synced-cron 1.3.2 <- pcci:sepsis-risk-model 0.1.11
* mongo@1.1.0 <- clinical:hl7-resource-observation 1.3.20
* mongo@1.1.0 <- clinical:hl7-resource-bundle 1.3.14 <- clinical:hl7-resource-diagnostic-report 1.5.12
* mongo@1.1.0 <- clinical:hl7-resource-diagnostic-report 1.5.12

Potentially incompatible change required to top-level dependency: es5-shim 4.7.3, was 4.8.0.
Constraints on package "es5-shim":
* es5-shim@4.7.0 <- top level
* es5-shim@~4.7.0 <- top level
* es5-shim@4.7.0 <- meteor-base 1.3.0

Potentially incompatible change required to top-level dependency: ecmascript 0.10.9, was 0.11.1.
Constraints on package "ecmascript":
* ecmascript@0.10.6 <- top level
* ecmascript@~0.10.6 <- top level
* ecmascript@0.10.0 <- webapp 1.5.0 <- autoupdate 1.4.0 <- hot-code-push 1.0.4 <- meteor-base 1.3.0
* ecmascript@0.10.0 <- webapp 1.5.0 <- meteor-base 1.3.0
* ecmascript@0.10.0 <- logging 1.1.20 <- meteor-platform 1.2.6 <- clinical:base-model 1.3.5 <- clinical:hl7-resource-bundle 1.3.14 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.10.0 <- logging 1.1.20 <- meteor-platform 1.2.6 <- clinical:base-model 1.3.5 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.10.0 <- logging 1.1.20 <- meteor-platform 1.2.6 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.9.0 <- ejson 1.1.0 <- aldeed:collection2 2.5.0 <- clinical:base-model 1.3.5 <- clinical:hl7-resource-bundle 1.3.14 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.9.0 <- ejson 1.1.0 <- aldeed:collection2 2.5.0 <- clinical:base-model 1.3.5 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.9.0 <- ejson 1.1.0 <- aldeed:collection2 2.5.0 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.9.0 <- ejson 1.1.0 <- mongo 1.4.7
* ecmascript@0.10.0 <- base64 1.0.11 <- ejson 1.1.0 <- aldeed:collection2 2.5.0 <- clinical:base-model 1.3.5 <- clinical:hl7-resource-bundle 1.3.14 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.10.0 <- base64 1.0.11 <- ejson 1.1.0 <- aldeed:collection2 2.5.0 <- clinical:base-model 1.3.5 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.10.0 <- base64 1.0.11 <- ejson 1.1.0 <- aldeed:collection2 2.5.0 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.10.0 <- base64 1.0.11 <- ejson 1.1.0 <- mongo 1.4.7
* ecmascript@0.10.0 <- routepolicy 1.0.13 <- ddp-server 2.1.2 <- ddp 1.4.0 <- allow-deny 1.1.0 <- mongo 1.4.7
* ecmascript@0.10.0 <- routepolicy 1.0.13 <- ddp-server 2.1.2 <- ddp 1.4.0 <- meteor-base 1.3.0
* ecmascript@0.10.0 <- routepolicy 1.0.13 <- webapp 1.5.0 <- meteor-base 1.3.0
* ecmascript@0.10.0 <- boilerplate-generator 1.4.0 <- webapp 1.5.0 <- autoupdate 1.4.0 <- hot-code-push 1.0.4 <- meteor-base 1.3.0
* ecmascript@0.10.0 <- boilerplate-generator 1.4.0 <- webapp 1.5.0 <- meteor-base 1.3.0
* ecmascript@0.4.3 <- webapp-hashing 1.0.9 <- webapp 1.5.0 <- autoupdate 1.4.0 <- hot-code-push 1.0.4 <- meteor-base 1.3.0
* ecmascript@0.4.3 <- webapp-hashing 1.0.9 <- webapp 1.5.0 <- meteor-base 1.3.0
* ecmascript@0.10.0 <- ddp-client 2.3.2 <- ddp 1.4.0 <- allow-deny 1.1.0 <- mongo 1.4.7
* ecmascript@0.10.0 <- ddp-client 2.3.2 <- ddp 1.4.0 <- meteor-base 1.3.0
* ecmascript@0.10.0 <- check 1.3.1 <- aldeed:collection2 2.5.0 <- clinical:base-model 1.3.5 <- clinical:hl7-resource-bundle 1.3.14 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.10.0 <- check 1.3.1 <- aldeed:collection2 2.5.0 <- clinical:base-model 1.3.5 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.10.0 <- check 1.3.1 <- aldeed:collection2 2.5.0 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.10.0 <- check 1.3.1 <- mongo 1.4.7
* ecmascript@0.10.0 <- random 1.1.0 <- aldeed:simple-schema 1.3.3 <- aldeed:collection2 2.5.0 <- clinical:base-model 1.3.5 <- clinical:hl7-resource-bundle 1.3.14 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.10.0 <- random 1.1.0 <- aldeed:simple-schema 1.3.3 <- aldeed:collection2 2.5.0 <- clinical:base-model 1.3.5 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.10.0 <- random 1.1.0 <- aldeed:simple-schema 1.3.3 <- aldeed:collection2 2.5.0 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.10.0 <- random 1.1.0 <- aldeed:simple-schema 1.3.3 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.10.0 <- random 1.1.0 <- mongo 1.4.7
* ecmascript@0.10.0 <- retry 1.1.0 <- autoupdate 1.4.0 <- hot-code-push 1.0.4 <- meteor-base 1.3.0
* ecmascript@0.10.0 <- id-map 1.1.0 <- binary-heap 1.0.10 <- mongo 1.4.7
* ecmascript@0.10.0 <- callback-hook 1.1.0 <- ddp-client 2.3.2 <- ddp 1.4.0 <- allow-deny 1.1.0 <- mongo 1.4.7
* ecmascript@0.10.0 <- callback-hook 1.1.0 <- ddp-client 2.3.2 <- ddp 1.4.0 <- meteor-base 1.3.0
* ecmascript@0.10.0 <- callback-hook 1.1.0 <- mongo 1.4.7
* ecmascript@0.10.0 <- ddp-common 1.4.0 <- ddp-client 2.3.2 <- ddp 1.4.0 <- allow-deny 1.1.0 <- mongo 1.4.7
* ecmascript@0.10.0 <- ddp-common 1.4.0 <- ddp-client 2.3.2 <- ddp 1.4.0 <- meteor-base 1.3.0
* ecmascript@0.10.0 <- reload 1.2.0 <- clinical:extended-api 2.2.4 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.10.0 <- socket-stream-client 0.1.0 <- ddp-client 2.3.2 <- ddp 1.4.0 <- allow-deny 1.1.0 <- mongo 1.4.7
* ecmascript@0.10.0 <- socket-stream-client 0.1.0 <- ddp-client 2.3.2 <- ddp 1.4.0 <- meteor-base 1.3.0
* ecmascript@0.10.0 <- diff-sequence 1.1.0 <- ddp-client 2.3.2 <- ddp 1.4.0 <- allow-deny 1.1.0 <- mongo 1.4.7
* ecmascript@0.10.0 <- diff-sequence 1.1.0 <- ddp-client 2.3.2 <- ddp 1.4.0 <- meteor-base 1.3.0
* ecmascript@0.10.0 <- diff-sequence 1.1.0 <- minimongo 1.4.4 <- mongo 1.4.7
* ecmascript@0.10.0 <- diff-sequence 1.1.0 <- mongo 1.4.7
* ecmascript@0.10.0 <- mongo-id 1.0.7 <- ddp-client 2.3.2 <- ddp 1.4.0 <- allow-deny 1.1.0 <- mongo 1.4.7
* ecmascript@0.10.0 <- mongo-id 1.0.7 <- ddp-client 2.3.2 <- ddp 1.4.0 <- meteor-base 1.3.0
* ecmascript@0.10.0 <- mongo-id 1.0.7 <- minimongo 1.4.4 <- mongo 1.4.7
* ecmascript@0.10.0 <- mongo-id 1.0.7 <- mongo 1.4.7
* ecmascript@0.10.0 <- ddp-server 2.1.2 <- ddp 1.4.0 <- allow-deny 1.1.0 <- mongo 1.4.7
* ecmascript@0.10.0 <- ddp-server 2.1.2 <- ddp 1.4.0 <- meteor-base 1.3.0
* ecmascript@0.9.0 <- minimongo 1.4.4 <- aldeed:collection2 2.5.0 <- clinical:base-model 1.3.5 <- clinical:hl7-resource-bundle 1.3.14 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.9.0 <- minimongo 1.4.4 <- aldeed:collection2 2.5.0 <- clinical:base-model 1.3.5 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.9.0 <- minimongo 1.4.4 <- aldeed:collection2 2.5.0 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.9.0 <- minimongo 1.4.4 <- mongo 1.4.7
* ecmascript@0.10.0 <- ordered-dict 1.1.0 <- blaze 2.3.2 <- blaze-html-templates 1.1.2
* ecmascript@0.10.0 <- server-render 0.3.1 <- es5-shim 4.7.3
* ecmascript@0.10.0 <- shim-common 0.1.0 <- es5-shim 4.7.3
* ecmascript@0.10.0 <- autoupdate 1.4.0 <- hot-code-push 1.0.4 <- meteor-base 1.3.0
* ecmascript@0.10.0 <- mongo 1.4.7
* ecmascript@0.9.0 <- allow-deny 1.1.0 <- mongo 1.4.7
* ecmascript@0.5.8 <- caching-html-compiler 1.1.3 <- templating-compiler 1.3.3 <- templating 1.3.2 <- blaze-html-templates 1.1.2
* ecmascript@0.9.0 <- caching-compiler 1.1.12 <- caching-html-compiler 1.1.3 <- templating-compiler 1.3.3 <- templating 1.3.2 <- blaze-html-templates 1.1.2
* ecmascript@0.9.0 <- caching-compiler 1.1.12 <- fourseven:scss 4.5.4 <- clinical:alert 2.1.3 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.5.8 <- templating-tools 1.1.2 <- caching-html-compiler 1.1.3 <- templating-compiler 1.3.3 <- templating 1.3.2 <- blaze-html-templates 1.1.2
* ecmascript@0.5.8 <- templating-tools 1.1.2 <- templating-compiler 1.3.3 <- templating 1.3.2 <- blaze-html-templates 1.1.2
* ecmascript@0.5.8 <- templating-compiler 1.3.3 <- templating 1.3.2 <- blaze-html-templates 1.1.2
* ecmascript@0.10.0 <- minifier-css 1.3.1 <- standard-minifier-css 1.4.1
* ecmascript@0.10.8 <- standard-minifier-js 2.3.4
* ecmascript@0.9.0 <- shell-server 0.3.1
* ecmascript@0.5.7 <- pcci:sepsis-risk-model 0.1.11
* ecmascript@0.9.0 <- reactive-dict 1.2.0 <- clinical:extended-api 2.2.4 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.4.1 <- react-meteor-data 0.2.16 <- clinical:glass-ui 2.1.6 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.4.1 <- react-meteor-data 0.2.16 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.4.0-beta.11 <- tmeasday:check-npm-versions 0.3.2 <- react-meteor-data 0.2.16 <- clinical:glass-ui 2.1.6 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.4.0-beta.11 <- tmeasday:check-npm-versions 0.3.2 <- react-meteor-data 0.2.16 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.9.0 <- clinical:glass-ui 2.1.6 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.4.3 <- coffeescript 1.0.17 <- tmeasday:publish-with-relations 0.2.0 <- clinical:base-model 1.3.5 <- clinical:hl7-resource-bundle 1.3.14 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.4.3 <- coffeescript 1.0.17 <- tmeasday:publish-with-relations 0.2.0 <- clinical:base-model 1.3.5 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.9.0 <- clinical:hl7-resource-observation 1.3.20
* ecmascript@0.1.5 <- clinical:alert 2.1.3 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.5.8 <- fourseven:scss 4.5.4 <- clinical:alert 2.1.3 <- clinical:hl7-resource-diagnostic-report 1.5.12
* ecmascript@0.9.0 <- clinical:hl7-resource-diagnostic-report 1.5.12

**With third faced following error. and firth too generates similar issues**

Errors prevented startup:

While selecting package versions:
error: Conflict: Constraint ddp-client@2.2.0 is not satisfied by ddp-client 1.2.9.
Constraints on package "ddp-client":
* ddp-client@~1.2.9 <- top level
* ddp-client@2.2.0 <- ddp 1.4.0 <- allow-deny 1.1.0 <- mongo 1.3.1
* ddp-client@2.2.0 <- ddp 1.4.0 <- meteor-base 1.2.0
* ddp-client@1.2.9 <- ddp-server 1.2.10 <- ddp 1.4.0 <- allow-deny 1.1.0 <- mongo 1.3.1
* ddp-client@1.2.9 <- ddp-server 1.2.10 <- ddp 1.4.0 <- meteor-base 1.2.0

Conflict: Constraint ddp-server@2.1.0 is not satisfied by ddp-server 1.2.10.
Constraints on package "ddp-server":
* ddp-server@~1.2.10 <- top level
* ddp-server@2.1.0 <- ddp 1.4.0 <- allow-deny 1.1.0 <- mongo 1.3.1
* ddp-server@2.1.0 <- ddp 1.4.0 <- meteor-base 1.2.0

Conflict: Constraint minifier-js@2.1.4 is not satisfied by minifier-js 1.2.18.
Constraints on package "minifier-js":
* minifier-js@~1.2.15 <- top level
* minifier-js@2.1.4 <- standard-minifier-js 2.2.3

Your application has errors. Waiting for file change.

**Comment by srikanthkonline** [comment]
Just FYI. I took version to 1.6.0.1, and removed all mongo, and other package constraints. But, that didn't solve the issue. And, the initial error with Observations object came up again.

**Comment by awatson1978** [comment]
Try the following...

```sh
# make sure you're in the webapp
cd webapp

# clear the meteor packages and databsae
meteor reset

# clear the npm modules
rm -rf node_modules

# reinstall npm dependencies
meteor npm install
```  

It appears you've corrupted the dependency tree by installing the latest Meteor, instead of sticking with Meteor on FHIR's version or the latest `clinical:METEOR` release.  It may be easier to simply scrap the entire directory, redownload, and start from scratch.  

We're going to update the README to include the release version.

**Comment by srikanthkonline** [comment]
I tried the meteor reset steps you suggested previous week. That didn't solve my issue. Also, I tried with fresh webapps by updating to 1.6.0.1 and then by adding packages. The same issue comes up afterv all the steps.

I am on windows. I run choco -force install meteor --version1.6.0.1. I see message that it was not installed and the package was not available at the source.

**Comment by awatson1978** [comment]
Aaaaah, Windows.  Yeah, we do all of our development on Macintosh.  Interesting.  

Are you doing an `import { Observations } from 'meteor/clinical:hl7-resource-observation`?  If so, try commenting out that line, and using the global that gets created automatically.

**Comment by srikanthkonline** [comment]
I did comment and tried now. But, still the same issue pops up. Please find the attached.

<img width="818" alt="appscr" src="https://user-images.githubusercontent.com/30258988/42762770-c86b9972-892e-11e8-9ce7-7700f7f559d1.png">

**Comment by srikanthkonline** [comment]
Going to try it out on Linux VM. Will keep updated.

**Comment by awatson1978** [comment]
I just updated the installation instructions on the sepsis calculator with steps that I just confirmed.  Check the calculator's README.

**Comment by srikanthkonline** [comment]
Thank you.
